
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://discovery:8761/eureka
    
endpoints:
  jmx:
    enabled: false
  shutdown:
    enabled: true
spring:
  jmx:
    enabled: false
  sleuth:
    sampler:
      percentage: 1.0
    log:
      json:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: none

management:
  security:
    enabled: false
  info:
    git:
      mode: full
      enabled: true
    env:
      enabled: true
    build:
      enabled: true
    defaults:
      enabled: true


logging:
  level:
    bzh.zomzog.zeshop: DEBUG
    org.springframework.cloud.config.server: INFO
    org.springframework.security: DEBUG
    javax.activation: WARN
    javax.mail: WARN
    javax.xml.bind: WARN
    ch.qos.logback: WARN
    com.codahale.metrics: WARN
    com.ryantenney: WARN
    com.sun: WARN
    com.zaxxer: WARN
    io.undertow: WARN
    io.undertow.websockets.jsr: ERROR
    org.ehcache: WARN
    org.apache: WARN
    org.apache.catalina.startup.DigesterFactory: OFF
    org.bson: WARN
    org.hibernate.validator: WARN
    org.hibernate: WARN
    org.hibernate.ejb.HibernatePersistence: OFF
    org.springframework: WARN
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.cache: WARN
    org.thymeleaf: WARN
    org.xnio: WARN
    springfox: WARN
    sun.rmi: WARN
    liquibase: WARN
    LiquibaseSchemaResolver: INFO
    sun.rmi.transport: WARN