logging:
    level:
        org.springframework.security: DEBUG

security:
    sessions: if_required
    
spring:
    mail:
      host: smtp.mailtrap.io
      port: 2525
      username: 73efcbf2fdf8f7
      password: 2b613b2738e97d
      

auth:
  mail:
    from: test@pony.test
    baseUrl: http://localhost