spring:
    devtools:
        restart:
            enabled: true

zuul:
  prefix: /api
  routes:
    cart:
      path: /cart-service/**
      serviceId: cart-service
      sensitiveHeaders: Cookie,Set-Cookie
    product:
      path: /product-service/**
      serviceId: product-service
      sensitiveHeaders: Cookie,Set-Cookie
    auth-service:
      path: /auth-service/**
      serviceId: auth-service
      sensitiveHeaders: Cookie,Set-Cookie

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false

hystrix:
  command:
    auth-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000